-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 23:33:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema whereismyhome
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema whereismyhome
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `whereismyhome` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `whereismyhome` ;

-- -----------------------------------------------------
-- Table `whereismyhome`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`user` (
  `user_id` VARCHAR(16) NOT NULL,
  `user_password` VARCHAR(16) NOT NULL,
  `user_name` VARCHAR(20) NOT NULL,
  `user_email` VARCHAR(20) NOT NULL,
  `user_phone` VARCHAR(20) NOT NULL,
  `register_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `token` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

insert into user
		(user_id, user_password, user_name, user_email, user_phone)
		values ("admin", 1234, "관리자", "ssafy@ssafy.com", "010-1234-5678");


-- -----------------------------------------------------
-- Table `whereismyhome`.`notice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`notice` (
  `notice_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(16) NULL DEFAULT NULL,
  `subject` VARCHAR(100) NULL DEFAULT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `hit` INT NULL DEFAULT 0,
  `register_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_address` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`notice_no`),
  INDEX `fk_notice_like_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_notice_like_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `whereismyhome`.`user` (`user_id`) ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`notice_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`notice_like` (
  `notice_no` INT NOT NULL,
  `user_id` VARCHAR(16) NOT NULL,
  `register_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_address` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`notice_no`, `user_id`),
  INDEX `fk_notice_like_notice1_idx` (`notice_no` ASC) VISIBLE,
  INDEX `fk_notice_like_user2_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_notice_like_notice1`
    FOREIGN KEY (`notice_no`)
    REFERENCES `whereismyhome`.`notice` (`notice_no`) ON DELETE CASCADE,
  CONSTRAINT `fk_notice_like_user2`
    FOREIGN KEY (`user_id`)
    REFERENCES `whereismyhome`.`user` (`user_id`) ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`notice_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`notice_comment` (
  `notice_comment_no` INT NOT NULL AUTO_INCREMENT,
  `notice_no` INT NOT NULL,
  `user_id` VARCHAR(16) NOT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `register_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_address` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`notice_comment_no`),
  INDEX `fk_notice_comment_notice1_idx` (`notice_no` ASC) VISIBLE,
  INDEX `fk_notice_comment_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_notice_comment_notice1`
    FOREIGN KEY (`notice_no`)
    REFERENCES `whereismyhome`.`notice` (`notice_no`) ON DELETE CASCADE,
  CONSTRAINT `fk_notice_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `whereismyhome`.`user` (`user_id`) ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`dongcode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`dongcode` (
  `dongCode` VARCHAR(10) NOT NULL,
  `sidoName` VARCHAR(30) NULL DEFAULT NULL,
  `gugunName` VARCHAR(30) NULL DEFAULT NULL,
  `dongName` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`dongCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`housedeal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`housedeal` (
  `no` BIGINT NOT NULL,
  `dealAmount` VARCHAR(20) NULL DEFAULT NULL,
  `dealYear` INT NULL DEFAULT NULL,
  `dealMonth` INT NULL DEFAULT NULL,
  `dealDay` INT NULL DEFAULT NULL,
  `area` VARCHAR(20) NULL DEFAULT NULL,
  `floor` VARCHAR(4) NULL DEFAULT NULL,
  `cancelDealType` VARCHAR(1) NULL DEFAULT NULL,
  `aptCode` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`no`),
  INDEX `housedeal_aptCode_houseinfo_aptCode_fk_idx` (`aptCode` ASC) VISIBLE,
  CONSTRAINT `housedeal_aptCode_houseinfo_aptCode_fk`
    FOREIGN KEY (`aptCode`)
    REFERENCES `whereismyhome`.`houseinfo` (`aptCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`houseinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`houseinfo` (
  `aptCode` BIGINT NOT NULL,
  `buildYear` INT NULL DEFAULT NULL,
  `roadName` VARCHAR(40) NULL DEFAULT NULL,
  `roadNameBonbun` VARCHAR(5) NULL DEFAULT NULL,
  `roadNameBubun` VARCHAR(5) NULL DEFAULT NULL,
  `roadNameSeq` VARCHAR(2) NULL DEFAULT NULL,
  `roadNameBasementCode` VARCHAR(1) NULL DEFAULT NULL,
  `roadNameCode` VARCHAR(7) NULL DEFAULT NULL,
  `dong` VARCHAR(40) NULL DEFAULT NULL,
  `bonbun` VARCHAR(4) NULL DEFAULT NULL,
  `bubun` VARCHAR(4) NULL DEFAULT NULL,
  `sigunguCode` VARCHAR(5) NULL DEFAULT NULL,
  `eubmyundongCode` VARCHAR(5) NULL DEFAULT NULL,
  `dongCode` VARCHAR(10) NULL DEFAULT NULL,
  `landCode` VARCHAR(1) NULL DEFAULT NULL,
  `apartmentName` VARCHAR(40) NULL DEFAULT NULL,
  `jibun` VARCHAR(10) NULL DEFAULT NULL,
  `lng` VARCHAR(30) NULL DEFAULT NULL,
  `lat` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`aptCode`),
  UNIQUE INDEX `UNIQUE` (`buildYear` ASC, `apartmentName` ASC, `jibun` ASC, `sigunguCode` ASC, `eubmyundongCode` ASC) INVISIBLE,
  INDEX `houseinfo_dongCode_dongcode_dongCode_fk_idx` (`dongCode` ASC) INVISIBLE,
  CONSTRAINT `houseinfo_dongCode_dongcode_dongCode_fk`
    FOREIGN KEY (`dongCode`)
    REFERENCES `whereismyhome`.`dongcode` (`dongCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`house_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`house_like` (
  `user_id` VARCHAR(16) NOT NULL,
  `aptCode` BIGINT NOT NULL,
  `register_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_address` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `aptCode`),
  INDEX `fk_house_like_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_house_like_houseinfo1_idx` (`aptCode` ASC) VISIBLE,
  CONSTRAINT `fk_house_like_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `whereismyhome`.`user` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_house_like_houseinfo1`
    FOREIGN KEY (`aptCode`)
    REFERENCES `whereismyhome`.`houseinfo` (`aptCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`area_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`area_like` (
  `user_id` VARCHAR(16) NOT NULL,
  `dongCode` VARCHAR(10) NOT NULL,
  `register_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_address` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`, `dongCode`),
  INDEX `fk_area_like_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_area_like_dongcode1_idx` (`dongCode` ASC) VISIBLE,
  CONSTRAINT `fk_area_like_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `whereismyhome`.`user` (`user_id`) ON DELETE CASCADE,
  CONSTRAINT `fk_area_like_dongcode1`
    FOREIGN KEY (`dongCode`)
    REFERENCES `whereismyhome`.`dongcode` (`dongCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `whereismyhome`.`qna`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `whereismyhome`.`question` (
  `question_no` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(16) NULL DEFAULT NULL,
  `subject` VARCHAR(100) NULL DEFAULT NULL,
  `content` VARCHAR(2000) NULL DEFAULT NULL,
  `register_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ip_address` VARCHAR(20) NULL DEFAULT NULL,
  `answer` VARCHAR(2000) NULL DEFAULT NULL,
  PRIMARY KEY (`question_no`),
  INDEX `fk_notice_like_user3_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_notice_like_user3`
    FOREIGN KEY (`user_id`)
    REFERENCES `whereismyhome`.`user` (`user_id`) ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
